### ISSUE TITLE
wifi.md dead link

### ISSUE THREAD

**Issue by thewasabiguy** [trevorbryant/cheatsheets#1]
the very last link in your cheat sheets times out and does not work

How to extract all handshakes from a capture file with several handshakes

**Comment by trevorbryant** [comment]
Is the link being blocked from the network you're on? It's currently working for me.

```
$ curl -I https://miloserdov.org/?p=1047
HTTP/2 200 
server: nginx
content-type: text/html; charset=UTF-8
vary: Accept-Encoding
x-powered-by: PHP/7.2.23
link: <https://miloserdov.org/index.php?rest_route=/>; rel="https://api.w.org/"
link: <https://miloserdov.org/?p=1047>; rel=shortlink
date: Mon, 04 Nov 2019 16:08:31 GMT
x-page-speed: 1.13.35.2-0
cache-control: max-age=0, no-cache
```

**Comment by thewasabiguy** [comment]
oh thats possible hold on let me switch networks

**Comment by thewasabiguy** [comment]
ok there is still a noticeable delay on different non corp network.  

issue closed

user issue not the cheat sheeet
